F
======================================================================
FAIL: test_1 (generate_parentheses_testSuite.Test.test_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/generate_parentheses_testSuite.py", line 6, in test_1
    self.assertEqual(generate_parentheses(3),32)
AssertionError: ['((()))', '(()())', '(())()', '()(())', '()()()'] != 32

----------------------------------------------------------------------
Ran 1 test in 0.012s

FAILED (failures=1)
Command exited with non-zero status 1
	Command being timed: "python3 -m unittest discover -s . -p *test*.py"
	User time (seconds): 0.14
	System time (seconds): 0.07
	Percent of CPU this job got: 27%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.79
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 14848
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2488
	Voluntary context switches: 89
	Involuntary context switches: 257
	Swaps: 0
	File system inputs: 0
	File system outputs: 576
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
